language: cpp
sudo: false

cache: apt

matrix:
    include:
        # OS X
        os: OSX
        osx_image: xcode6.4
        compiler: clang
        
        os: OSX
        osx_image: xcode7.1
        compiler: clang
        
        # Linux
        os: linux
        compiler: gcc
    
script:
    cd ${TRAVIS_BUILD_DIR}
    cd prosoft/core/tests
    rake
    
