language: cpp

sudo: false

cache:
    apt: true
    directories:
        - $HOME/depend

matrix:
    include:
        # OS X
      - os: osx
        osx_image: xcode6.4
        compiler: clang
        env: PSCC=clang PSCXX=clang++

      - os: osx
        osx_image: xcode7.2
        compiler: clang
        env: PSCC=clang PSCXX=clang++

        # Linux
      - os: linux
        compiler: gcc
        addons: &gcc48
            apt:
                sources: ['ubuntu-toolchain-r-test']
                packages: ['gcc-4.8', 'g++-4.8', 'libacl1-dev']
        env: PSCC=gcc-4.8 PSCXX=g++-4.8

      - os: linux
        compiler: gcc
        addons: &gcc49
            apt:
                sources: ['ubuntu-toolchain-r-test']
                packages: ['gcc-4.9', 'g++-4.9', 'libacl1-dev']
        env: PSCC=gcc-4.9 PSCXX=g++-4.9

      - os: linux
        compiler: gcc
        addons: &gcc5
            apt:
                sources: ['ubuntu-toolchain-r-test']
                packages: ['gcc-5', 'g++-5', 'libacl1-dev']
        # onig apparently has some leaks (or ASAN thinks it does), disable for now
        env: PSCC=gcc-5 PSCXX=g++-5 ASAN_OPTIONS=detect_leaks=0
        # enable Ubuntu 14 image
        sudo: required
        dist: trusty
        
install:
    - |
        INSTALL_DIR="${HOME}/depend"
        mkdir -p "${INSTALL_DIR}" "${INSTALL_DIR}/bin" "${INSTALL_DIR}/man" "${INSTALL_DIR}/share"
        if [ ! -x "${INSTALL_DIR}/bin/cmake" ]; then
            ${TRAVIS_BUILD_DIR}/depend/get_cmake.sh --prefix ${INSTALL_DIR}
        fi
        export PATH=${INSTALL_DIR}/bin:${PATH}

before_script:
    - cd ${TRAVIS_BUILD_DIR}
    - cd prosoft/core/tests
    - export CC=${PSCC} CXX=${PSCXX}

script:
    - rake

after_success:
  - bash <(curl -s https://codecov.io/bash) || true
