language: cpp

cache: apt

matrix:
    include:
        # OS X
      - os: OSX
        osx_image: xcode6.4
        compiler: clang

      - os: OSX
        osx_image: xcode7.1
        compiler: clang

        # Linux
      - os: linux
        compiler: gcc
        addons: &gcc48
            apt:
                sources: ['ubuntu-toolchain-r-test']
                packages: ['g++-4.8']
        env: CXX=g++-4.8

      - os: linux
        compiler: gcc
        addons: &gcc49
            apt:
                sources: ['ubuntu-toolchain-r-test']
                packages: ['g++-4.9']
        env: CXX=g++-4.9

      - os: linux
        compiler: gcc
        addons: &gcc5
            apt:
                sources: ['ubuntu-toolchain-r-test']
                packages: ['g++-5']
        env: CXX=g++-5

install:
    - sh ${TRAVIS_BUILD_DIR}/prosoft/depend/get_cmake.sh 3.4.1

script:
    - cd ${TRAVIS_BUILD_DIR}
    - cd prosoft/core/tests
    - rake
