language: cpp

sudo: false

cache:
    apt: true
    directories:
        - $HOME/depend

matrix:
    include:
      # latest xcode for macOS 10.12
      - os: osx
        osx_image: xcode9.2
        compiler: clang
        env: PSCC=clang PSCXX=clang++

      # latest xcode for macOS 10.13
      - os: osx
        osx_image: xcode10.1
        compiler: clang
        env: PSCC=clang PSCXX=clang++

      # latest xcode for macOS 10.14
      - os: osx
        osx_image: xcode11.3
        compiler: clang
        env: PSCC=clang PSCXX=clang++

      # latest xcode for macOS 10.15
      - os: osx
        osx_image: xcode12.2
        compiler: clang
        env: PSCC=clang PSCXX=clang++

      # latest gcc for Ubuntu Xenial 16.04
      - os: linux
        dist: xenial
        env: PSCC=gcc PSCXX=g++
        addons:
            apt:
                packages:
                    - libacl1-dev

      # latest gcc for Ubuntu Bionic 18.04
      - os: linux
        dist: bionic
        env: PSCC=gcc PSCXX=g++
        addons:
            apt:
                packages:
                    - libacl1-dev

      # latest gcc for Ubuntu Focal 20.04
      - os: linux
        dist: focal
        env: PSCC=gcc PSCXX=g++
        addons:
            apt:
                packages:
                    - libacl1-dev
        
install:
    - |
        INSTALL_DIR="${HOME}/depend"
        mkdir -p "${INSTALL_DIR}" "${INSTALL_DIR}/bin" "${INSTALL_DIR}/man" "${INSTALL_DIR}/share"
        if [ ! -x "${INSTALL_DIR}/bin/cmake" ]; then
            ${TRAVIS_BUILD_DIR}/depend/get_cmake.sh --prefix ${INSTALL_DIR}
        fi
        export PATH=${INSTALL_DIR}/bin:${PATH}

before_script:
    - cd ${TRAVIS_BUILD_DIR}
    - cd prosoft/core/tests
    - export CC=${PSCC} CXX=${PSCXX}

script:
    - rake

after_success:
  - bash <(curl -s https://codecov.io/bash) || true
