language: cpp

sudo: false

cache:
    apt: true
    directories:
        - $HOME/depend

matrix:
    include:
        # OS X
      - os: osx
        osx_image: xcode7.3
        compiler: clang
        env: PSCC=clang PSCXX=clang++

      - os: osx
        osx_image: xcode8.3
        compiler: clang
        env: PSCC=clang PSCXX=clang++

      - os: osx
        osx_image: xcode9
        compiler: clang
        env: PSCC=clang PSCXX=clang++

        # Linux
        # Containers are disabled because the filesystem iterator tests are failing inexplicably.
        # Perhaps something to do with AUFS.
        # However I did download the docker instance and run the tests manually and they passed.
      - os: linux
        compiler: gcc
        addons: &gcc48
            apt:
                sources: ['ubuntu-toolchain-r-test']
                packages: ['gcc-4.8', 'g++-4.8', 'libacl1-dev']
        env: PSCC=gcc-4.8 PSCXX=g++-4.8
        sudo: required

      - os: linux
        compiler: gcc
        addons: &gcc49
            apt:
                sources: ['ubuntu-toolchain-r-test']
                packages: ['gcc-4.9', 'g++-4.9', 'libacl1-dev']
        env: PSCC=gcc-4.9 PSCXX=g++-4.9
        dist: trusty
        sudo: required

      - os: linux
        compiler: gcc
        addons: &gcc5
            apt:
                sources: ['ubuntu-toolchain-r-test']
                packages: ['gcc-5', 'g++-5', 'libacl1-dev']
        env: PSCC=gcc-5 PSCXX=g++-5
        sudo: required
        dist: trusty
        
      - os: linux
        compiler: gcc
        addons: &gcc6
            apt:
                sources: ['ubuntu-toolchain-r-test']
                packages: ['gcc-6', 'g++-6', 'libacl1-dev']
        env: PSCC=gcc-6 PSCXX=g++-6
        sudo: required
        dist: trusty

      - os: linux
        compiler: gcc
        addons: &gcc7
            apt:
                sources: ['ubuntu-toolchain-r-test']
                packages: ['gcc-7', 'g++-7', 'libacl1-dev']
        env: PSCC=gcc-7 PSCXX=g++-7
        sudo: required
        dist: trusty
        
install:
    - |
        INSTALL_DIR="${HOME}/depend"
        mkdir -p "${INSTALL_DIR}" "${INSTALL_DIR}/bin" "${INSTALL_DIR}/man" "${INSTALL_DIR}/share"
        if [ ! -x "${INSTALL_DIR}/bin/cmake" ]; then
            ${TRAVIS_BUILD_DIR}/depend/get_cmake.sh --prefix ${INSTALL_DIR}
        fi
        export PATH=${INSTALL_DIR}/bin:${PATH}

before_script:
    - cd ${TRAVIS_BUILD_DIR}
    - cd prosoft/core/tests
    - export CC=${PSCC} CXX=${PSCXX}

script:
    - rake

after_success:
  - bash <(curl -s https://codecov.io/bash) || true
