version: 1.0.{build}

skip_tags: true

deploy: off

image:
  - Visual Studio 2015
  - Visual Studio 2017

install:
  # As of June 2018, TLS 1.2 is required to connect to rubygems.org. The default ruby is 1.9.3 and doesn't support TLS 1.2.
  # https://github.com/rubygems/rubygems/issues/1912
  # https://help.appveyor.com/discussions/problems/15052-unable-to-download-data-from-httpsrubygemsorg
  - set PATH=C:\Ruby25\bin;%PATH%
  - gem update --system
  - gem install rake -f -q

build_script:
- cmd: >-
    cd prosoft/core/tests && rake

test: off
