version: 1.0.{build}

skip_tags: true

deploy: off

os: Visual Studio 2015

install:
  - gem update --system
  - gem install rake -f -q

build_script:
- cmd: >-
    cd prosoft/core/tests && rake

test: off
