version: 1.0.{build}

skip_tags: true

deploy: off

image:
  - Visual Studio 2015
  - Visual Studio 2017
  - Visual Studio 2019

install:
  - set PATH=C:\Ruby25-x64\bin;%PATH%
  - ruby --version
  # Install conan
  - set PYTHON=C:\Python38-x64
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - python --version
  - pip --version
  - pip install --upgrade conan
  - conan --version
  # Check versions
  - cmake --version
  - rake --version

build_script:
- cmd: >-
    cd prosoft/core/tests && rake

test: off
